version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 1

  - package-ecosystem: "actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 1